# Generated by Django 4.0.8 on 2022-11-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='budgetedamount',
            field=models.PositiveIntegerField(),
        ),
    ]
