# Generated by Django 4.0.8 on 2022-11-29 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0007_rating_purchaseorder_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='reviewee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluated_vendor', to='projects.vendor'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluator', to=settings.AUTH_USER_MODEL),
        ),
    ]
