# Generated by Django 4.0.8 on 2022-11-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_rating_reviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('In Preparation', 'In Preparation'), ('Requested', 'Requested'), ('Assigned-waiting', 'Assigned-waiting'), ('In Progress', 'In Progress'), ('Overdue', 'Overdue'), ('Delivered', 'Delivered'), ('Complained', 'Complained'), ('Approved', 'Approved')], default='In Preparation', max_length=100),
        ),
    ]
