# Generated by Django 4.0.8 on 2022-12-06 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobrate', to='projects.job'),
        ),
    ]
