# Generated by Django 4.0.8 on 2023-06-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_vendor_education_level_vendor_language_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paymentTerms',
            field=models.CharField(choices=[('30 days', '30 days'), ('45 days', '45 days'), ('60 days', '60 days'), ('Contract', 'Contract')], default='30 days', max_length=100),
        ),
    ]
