# Generated by Django 4.0.8 on 2024-12-31 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_project_due_date'),
        ('projects', '0018_project_due_date_alter_invoice_paymentterms'),
    ]

    operations = [
    ]
