version: "3.9"

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
    - .:/code
    ports:
    - 8000:8000
    depends_on:
    - db
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-)g++xac#_*(!6746w^w=b1h8s61s9rpd#3p2-qmz71)@#mku0x"
      - "DJANGO_DEBUG=True"

  db:
    image: postgres:13
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    environment:
    - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
  postgres_data: